### PR TITLE
Card.js Refactored to Styled-Components

### LINKED ISSUE #20: Improve Card styled component
By the time, the `Card` component is using styled-component as well as styles on a separated stylesheet.

The goal of this task is to merge all styles of the Card on the `Container` styled-component definition inside that the `Card.js` component file.

### PR DESCRIPTION
**Pull request by mmajdanski**
# Description

Refactored Card.js to not use any CSS file, but rather Style Components

Fixes #20 

# Checklist:

- [X ] I'm already part of the contributors list. Don't know how to add yourself? You can use [this tool](https://github.com/jfmengels/all-contributors-cli).
- [ ] Tests are included.

### CODE REVIEW

**Comment by Wgil** [comment]
Bro, we need to test the styled components in order to keep the coverage at 100%. I think that testing only how it reacts to the prop changes would be enough but I'm not pretty sure if doing so will make it reach at 100%. Would you want to give it a try or you prefer me to do it?

Here is a guide on how we could approach this https://medium.com/styled-components/effective-testing-for-styled-components-67982eb7d42b

Also, there are some tests already created in the project so you can have a guide.

**Comment by mmajdanski** [comment]
Sure thing. I'll give it a shot. I'll let you know if I need assistance with that.

**Comment by Wgil** [comment]
Great! Our game is alive now! take a look to the development branch, cards can be paired now

**Comment by Wgil** [comment]
I'm closing this, I merged the changes manually.

**Comment by Wgil** [comment]
That's great! I'll be working on the card component by the end of the week.
If you want you can try to add some tests to it.

**Pull request closed without merging**
